DROP TABLE IF EXISTS VEICOLI;

CREATE TABLE VEICOLI
(
    ID        INTEGER PRIMARY KEY,
    CODICE    TEXT,
    TIPO      TEXT,
    MARCA     TEXT,
    FREQUENZA REAL
);

DROP TABLE IF EXISTS OSTACOLI;

CREATE TABLE OSTACOLI
(
    ID         INTEGER PRIMARY KEY,
    NOME_SRC   TEXT,
    NOME       TEXT,
    IMMAGINE   TEXT,
    COLLISIONE TEXT
);