DROP TABLE IF EXISTS VEICOLI;

CREATE TABLE VEICOLI
(
    CODICE       TEXT PRIMARY KEY,
    MARCA        TEXT,
    FREQUENZA    REAL,
    COLORE       TEXT,
    URL_IMMAGINE TEXT,
    COLLISIONE   TEXT
);

DROP TABLE IF EXISTS OSTACOLI;

CREATE TABLE OSTACOLI
(
    NOME_SRC     TEXT PRIMARY KEY,
    NOME         TEXT,
    URL_IMMAGINE TEXT,
    COLLISIONE   TEXT
);