DROP TABLE IF EXISTS VEICOLI;

CREATE TABLE VEICOLI
(
    CODICE       TEXT PRIMARY KEY,
    MARCA        TEXT,
    URL_IMMAGINE TEXT
);

DROP TABLE IF EXISTS OSTACOLI;

CREATE TABLE OSTACOLI
(
    NOME_SRC     TEXT PRIMARY KEY,
    NOME         TEXT,
    URL_IMMAGINE TEXT
);