INSERT INTO VEICOLI(CODICE, TIPO, MARCA, FREQUENZA)
VALUES ('V001', 'AUTO', 'FERRARI', 2.4);
INSERT INTO VEICOLI(CODICE, TIPO, MARCA, FREQUENZA)
VALUES ('V002', 'MOTO', 'DUCATI', 2.4);
INSERT INTO VEICOLI(CODICE, TIPO, MARCA, FREQUENZA)
VALUES ('V003', 'CAMION', 'MERCEDES', 2.4);

INSERT INTO OSTACOLI(NOME_SRC, NOME, IMMAGINE, COLLISIONE)
VALUES ('cone', '', 'cone.png', '{}');
INSERT INTO OSTACOLI(NOME_SRC, NOME, IMMAGINE, COLLISIONE)
VALUES ('hole', '', 'hole.png', '{}');
INSERT INTO OSTACOLI(NOME_SRC, NOME, IMMAGINE, COLLISIONE)
VALUES ('oil', '', 'oil.png', '{}');
INSERT INTO OSTACOLI(NOME_SRC, NOME, IMMAGINE, COLLISIONE)
VALUES ('roadblock', '', 'roadblock.png', '{}');
INSERT INTO OSTACOLI(NOME_SRC, NOME, IMMAGINE, COLLISIONE)
VALUES ('tree', '', 'tree.png', '{}');