INSERT INTO VEICOLI(CODICE, MARCA, FREQUENZA, COLORE, URL_IMMAGINE, COLLISIONE)
VALUES ('V001', 'FERRARI', 27.0, 'ROSSO', 'red_car.png', '{}');

INSERT INTO VEICOLI(CODICE, MARCA, FREQUENZA, COLORE, URL_IMMAGINE, COLLISIONE)
VALUES ('V002', 'MERCEDES', 40.0, 'BIANCO', 'white_car.png', '{}');

INSERT INTO VEICOLI(CODICE, MARCA, FREQUENZA, COLORE, URL_IMMAGINE, COLLISIONE)
VALUES ('V003', 'PORSCHE', 53.0, 'YELLOW', 'yellow_car.png', '{}');

INSERT INTO OSTACOLI(NOME_SRC, NOME, URL_IMMAGINE, COLLISIONE)
VALUES ('CONE', '', 'cone.png', '{}');
INSERT INTO OSTACOLI(NOME_SRC, NOME, URL_IMMAGINE, COLLISIONE)
VALUES ('HOLE', '', 'hole.png', '{}');
INSERT INTO OSTACOLI(NOME_SRC, NOME, URL_IMMAGINE, COLLISIONE)
VALUES ('OIL', '', 'oil.png', '{}');
INSERT INTO OSTACOLI(NOME_SRC, NOME, URL_IMMAGINE, COLLISIONE)
VALUES ('ROADBLOCK', '', 'roadblock.png', '{}');
INSERT INTO OSTACOLI(NOME_SRC, NOME, URL_IMMAGINE, COLLISIONE)
VALUES ('TREE', '', 'tree.png', '{}');